import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import './MaintenancePaper.css';

const MaintenancePaper = () => {
  const { maintenanceId } = useParams();
  const navigate = useNavigate();
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchMaintenancePaper();
  }, [maintenanceId]);

  const fetchMaintenancePaper = async () => {
    try {
      setLoading(true);
      const response = await axios.get(
        `${import.meta.env.VITE_API_URL}/api/maintenance-records/${maintenanceId}/maintenance_paper/`
      );
      setReportData(response.data);
      setError(null);
    } catch (err) {
      console.error('Error fetching maintenance paper:', err);
      setError('Failed to load maintenance paper. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    // Optional: Implement PDF generation if needed
    alert('PDF download functionality can be implemented using a library like jsPDF or html2pdf');
  };

  if (loading) {
    return (
      <div className="maintenance-paper-container">
        <div className="loading">Loading maintenance paper...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="maintenance-paper-container">
        <div className="error-message">{error}</div>
        <button onClick={() => navigate(-1)}>Go Back</button>
      </div>
    );
  }

  if (!reportData) {
    return (
      <div className="maintenance-paper-container">
        <div className="error-message">No data available</div>
        <button onClick={() => navigate(-1)}>Go Back</button>
      </div>
    );
  }

  const { asset, current_maintenance, maintenance_history, statistics } = reportData;

  return (
    <div className="maintenance-paper-container">
      {/* Action buttons - hidden when printing */}
      <div className="action-buttons no-print">
        <button onClick={() => navigate(-1)} className="btn-back">
          ← Back
        </button>
        <button onClick={handlePrint} className="btn-print">
          🖨️ Print
        </button>
        <button onClick={handleDownloadPDF} className="btn-download">
          📄 Download PDF
        </button>
      </div>

      {/* Maintenance Paper Content */}
      <div className="maintenance-paper">
        {/* Header */}
        <div className="paper-header">
          <h1>Asset Maintenance Report</h1>
          <div className="report-meta">
            <p><strong>Generated:</strong> {new Date(reportData.report_generated_at).toLocaleString()}</p>
            <p><strong>Generated By:</strong> {reportData.generated_by}</p>
          </div>
        </div>

        {/* Asset Information */}
        <section className="paper-section">
          <h2>Asset Information</h2>
          <div className="info-grid">
            <div className="info-row">
              <span className="info-label">Asset Name:</span>
              <span className="info-value">{asset.item_name}</span>
            </div>
            <div className="info-row">
              <span className="info-label">Instance Code:</span>
              <span className="info-value">{asset.instance_code}</span>
            </div>
            <div className="info-row">
              <span className="info-label">Category:</span>
              <span className="info-value">{asset.category}</span>
            </div>
            <div className="info-row">
              <span className="info-label">Current Location:</span>
              <span className="info-value">{asset.current_location}</span>
            </div>
            <div className="info-row">
              <span className="info-label">Condition:</span>
              <span className="info-value">{asset.condition}</span>
            </div>
            <div className="info-row">
              <span className="info-label">Status:</span>
              <span className="info-value">{asset.status}</span>
            </div>
            {asset.assigned_to && (
              <div className="info-row">
                <span className="info-label">Assigned To:</span>
                <span className="info-value">{asset.assigned_to}</span>
              </div>
            )}
            {asset.purchase_date && (
              <div className="info-row">
                <span className="info-label">Purchase Date:</span>
                <span className="info-value">{new Date(asset.purchase_date).toLocaleDateString()}</span>
              </div>
            )}
          </div>
        </section>

        {/* Current Maintenance Details */}
        <section className="paper-section">
          <h2>Current Maintenance Details</h2>
          <div className="info-grid">
            <div className="info-row">
              <span className="info-label">Maintenance Type:</span>
              <span className="info-value">{current_maintenance.maintenance_type}</span>
            </div>
            <div className="info-row">
              <span className="info-label">Status:</span>
              <span className="info-value status-badge">{current_maintenance.status}</span>
            </div>
            <div className="info-row">
              <span className="info-label">Scheduled Date:</span>
              <span className="info-value">{new Date(current_maintenance.scheduled_date).toLocaleDateString()}</span>
            </div>
            {current_maintenance.scheduled_by && (
              <div className="info-row">
                <span className="info-label">Scheduled By:</span>
                <span className="info-value">{current_maintenance.scheduled_by}</span>
              </div>
            )}
            {current_maintenance.completed_date && (
              <div className="info-row">
                <span className="info-label">Completed Date:</span>
                <span className="info-value">{new Date(current_maintenance.completed_date).toLocaleDateString()}</span>
              </div>
            )}
            {current_maintenance.cost && (
              <div className="info-row">
                <span className="info-label">Cost:</span>
                <span className="info-value">₹{parseFloat(current_maintenance.cost).toLocaleString()}</span>
              </div>
            )}
            {current_maintenance.vendor_name && (
              <div className="info-row">
                <span className="info-label">Vendor:</span>
                <span className="info-value">{current_maintenance.vendor_name}</span>
              </div>
            )}
          </div>
          {current_maintenance.description && (
            <div className="info-row full-width">
              <span className="info-label">Description:</span>
              <p className="info-value">{current_maintenance.description}</p>
            </div>
          )}
          {current_maintenance.notes && (
            <div className="info-row full-width">
              <span className="info-label">Notes:</span>
              <p className="info-value">{current_maintenance.notes}</p>
            </div>
          )}
        </section>

        {/* Maintenance History */}
        {maintenance_history && maintenance_history.length > 0 && (
          <section className="paper-section">
            <h2>Maintenance History (Last 10 Completed)</h2>
            <table className="history-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Type</th>
                  <th>Description</th>
                  <th>Cost</th>
                  <th>Vendor</th>
                  <th>Scheduled By</th>
                </tr>
              </thead>
              <tbody>
                {maintenance_history.map((record, index) => (
                  <tr key={index}>
                    <td>{new Date(record.completed_date).toLocaleDateString()}</td>
                    <td>{record.maintenance_type}</td>
                    <td>{record.description || '-'}</td>
                    <td>{record.cost ? `₹${parseFloat(record.cost).toLocaleString()}` : '-'}</td>
                    <td>{record.vendor_name || '-'}</td>
                    <td>{record.scheduled_by || '-'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* Statistics */}
        <section className="paper-section">
          <h2>Maintenance Statistics</h2>
          <div className="stats-grid">
            <div className="stat-card">
              <div className="stat-value">{statistics.total_maintenance_count}</div>
              <div className="stat-label">Total Maintenance Records</div>
            </div>
            <div className="stat-card">
              <div className="stat-value">{statistics.completed_count}</div>
              <div className="stat-label">Completed</div>
            </div>
            <div className="stat-card">
              <div className="stat-value">{statistics.scheduled_count}</div>
              <div className="stat-label">Scheduled</div>
            </div>
            <div className="stat-card">
              <div className="stat-value">{statistics.in_progress_count}</div>
              <div className="stat-label">In Progress</div>
            </div>
            <div className="stat-card highlight">
              <div className="stat-value">₹{parseFloat(statistics.total_cost || 0).toLocaleString()}</div>
              <div className="stat-label">Total Maintenance Cost</div>
            </div>
          </div>
        </section>

        {/* Footer */}
        <div className="paper-footer">
          <p>This is an auto-generated report from the Asset Management System</p>
          <p>Report ID: {current_maintenance.id} | Generated: {new Date(reportData.report_generated_at).toLocaleString()}</p>
        </div>
      </div>
    </div>
  );
};

export default MaintenancePaper;
